### PR TITLE
WIP Keep credentials private in enterprise-suite/scripts/install-es.sh

### PR DESCRIPTION
**Pull request by marcoderama**

### CODE REVIEW

**Comment by marcoderama** [comment]
These changes are failing for the front-end tests.  (The install isn't working.)  I suspect it has something to do with writing/reading the credentials from a file but haven't been able to crack it.  Gonna have to come back to this later.

**Comment by jsravn** [comment]
@marcoderama Looks like the `/tmp` file is misformatted or something. Because the image pull is failing as unauthorized. Are you sure it's created correctly?

**Comment by marcoderama** [comment]
I added some debug lines to help see what's going on.  `CREDS` is the `$CREDS` temp file that I'm writing the credentials to.  I gave everyone read permissions to see if that helped.  No, but left that change in for now.  In this version, I'm writing the bogus credentials `username`/`password` so I can dump the file contents and see what's in there

```
ES_LOCAL_CHART=../docs/enterprise-suite-0.10.4.tgz \
    ./scripts/install-es.sh --wait --set minikube=true,podUID=10001 
CREDS post-create: -rw-r--r-- 1 travis travis 0 Oct  1 22:39 /tmp/creds.h4uWgg
warning: --version has not been set, helm will use the latest available version. It is recommended to use an explicit version.
CREDS post-write: -rw-r--r-- 1 travis travis 72 Oct  1 22:39 /tmp/creds.h4uWgg
# I dump the contents of $CREDS here
imageCredentials.username: username
imageCredentials.password: password
helm status enterprise-suite > /dev/null 2>&1
CREDS pre-use: -rw-r--r-- 1 travis travis 72 Oct  1 22:39 /tmp/creds.h4uWgg
helm install ../docs/enterprise-suite-0.10.4.tgz --name=enterprise-suite --namespace=lightbend --values /tmp/creds.h4uWgg --wait --set minikube=true,podUID=10001
```

**Comment by marcoderama** [comment]
I've changed things so that 'normally', the credentials are written to a file and `helm` invoked with `--values`.  That way the credentials won't show up in a log.  If the `TRAVIS` env var is set, we revert to using `--set`.  The credentials are still not logged because Travis obfuscates them.

Perhaps not the beautiful solution, but it works...

**Comment by marcoderama** [comment]
Next time I'll remember to remove that 'WIP' before I merge...  sigh...

**Pull request merged**
