### PR TITLE
Quicker smoke

### PR DESCRIPTION
**Pull request by dbrinegar**
Run all the smoke tests in parallel.

This exposed some wait problems on the port-forward test, so that one has busy_wait
for kubectl and es-console now.  It also turned up a `ps` output format bug there.

It also has Travis output issues so added "sponge" to try to emit all the test output at
once and avoid intermingled console output.  On Travis this seems particularly bad as
test output can be obliterated, somehow, console output not captured.

And it turned up timing issues with smoke_prometheus, so now we wait for
kube-state-metrics and node-exporter.

Is a relatively small savings in run time, but hey.  found a bunch of issues worth fixing.

looks like maybe 4-1/2 minutes instead of 5-1/2 minutes, maybe will bring variance in a little

### CODE REVIEW

**Comment by dbrinegar** [comment]
```
(quicker-smoke)$ time ./smoketest 
==== Running smoke_ingress
==== Running smoke_ingress-tls
==== Running smoke_port-forward
==== Running smoke_prometheus
==== Running smoke_proxy
==== Running smoke_services
deployment.extensions/es-test created
service/es-test created
PASS: Prometheus has at least three scrapes
PASS: Prometheus scraping 5 targets
PASS: Prometheus "warn" logs
PASS: Prometheus "err" logs
PASS: timeseries: prometheus_notifications_dropped_rate
PASS: timeseries: prometheus_notification_queue_percent
PASS: timeseries: prometheus_rule_evaluation_failures_rate
PASS: timeseries: prometheus_target_scrapes_exceeded_sample_limit_rate
PASS: timeseries: prometheus_tsdb_reloads_failures_rate
PASS: timeseries: prometheus_config_last_reload_successful
PASS: timeseries: prometheus_target_sync_percent
PASS: timeseries: model{name="prometheus_notifications_dropped"}
PASS: timeseries: health{name="prometheus_notifications_dropped"}
PASS: timeseries: model{name="prometheus_notification_queue"}
PASS: timeseries: health{name="prometheus_notification_queue"}
PASS: timeseries: model{name="prometheus_rule_evaluation_failures"}
PASS: timeseries: health{name="prometheus_rule_evaluation_failures"}
PASS: timeseries: model{name="prometheus_target_too_many_metrics"}
PASS: timeseries: health{name="prometheus_target_too_many_metrics"}
PASS: timeseries: model{name="prometheus_tsdb_reloads_failures"}
PASS: timeseries: health{name="prometheus_tsdb_reloads_failures"}
PASS: timeseries: model{name="prometheus_target_down"}
PASS: timeseries: health{name="prometheus_target_down"}
PASS: timeseries: model{name="prometheus_config_reload_failed"}
PASS: timeseries: health{name="prometheus_config_reload_failed"}
PASS: timeseries: model{name="prometheus_scrape_time"}
PASS: timeseries: health{name="prometheus_scrape_time"}
PASS: timeseries: count({workload=~".+", namespace=""})
PASS: timeseries: health{workload="",name!~"node.*|kube_node.*|prometheus_target_down|scrape_time"}
PASS: timeseries: kube_pod_info{workload=~".+"}
PASS: timeseries: kube_pod_info{workload=""}
PASS: timeseries: kube_node_pressure
PASS: timeseries: kube_pod_ready
PASS: timeseries: kube_pod_container_restarts_rate
PASS: timeseries: kube_pod_failed
PASS: timeseries: kube_pod_not_running
PASS: timeseries: kube_workload_generation_lag
PASS: timeseries: model{name="kube_node_pressure"}
PASS: timeseries: health{name="kube_node_pressure"}
PASS: timeseries: model{name="restarts"}
PASS: timeseries: health{name="restarts"}
PASS: timeseries: model{name="kube_pod_not_ready"}
PASS: timeseries: health{name="kube_pod_not_ready"}
PASS: timeseries: model{name="kube_pod_not_running"}
PASS: timeseries: health{name="kube_pod_not_running"}
PASS: timeseries: model{name="kube_workload_generation_lag"}
PASS: timeseries: health{name="kube_workload_generation_lag"}
PASS: kube-state-metrics "failed" logs
PASS: kube-state-metrics "warn" logs
PASS: kube-state-metrics "err" logs
PASS: timeseries: node_cpu_percent
PASS: timeseries: node_memory_usable_percent
PASS: timeseries: node_filesystem_free_percent
PASS: timeseries: node_network_error_rate
PASS: timeseries: model{name="node_high_cpu"}
PASS: timeseries: health{name="node_high_cpu"}
PASS: timeseries: model{name="node_memory_pressure"}
PASS: timeseries: health{name="node_memory_pressure"}
PASS: timeseries: model{name="node_network_errors"}
PASS: timeseries: health{name="node_network_errors"}
PASS: node-exporter "failed" logs
PASS: node-exporter "warn" logs
PASS: node-exporter "err" logs
PASS: ES2 console accessible via http://127.0.0.1:52770
All smoke_port-forward tests pass.  PASS: 1  FAIL: 0
PASS: ES2 console accessible via http://192.168.99.100:30080
PASS: grafana service accessible via http://192.168.99.100:30030
PASS: prometheus service accessible via http://192.168.99.100:30090
PASS: alertmanager accessible via http://192.168.99.100:30093
PASS: grafana service accessible via http://192.168.99.100:30080/service/grafana
PASS: prometheus service accessible via http://192.168.99.100:30080/service/prometheus
PASS: es-monitor-api service accessible via http://192.168.99.100:30080/service/es-monitor-api
All smoke_services tests pass.  PASS: 7  FAIL: 0
PASS: es-monitor-api service accessible via http://127.0.0.1:52812/api/v1/namespaces/lightbend/services/es-monitor-api:80/proxy
PASS: prometheus service accessible via http://127.0.0.1:52812/api/v1/namespaces/lightbend/services/expose-prometheus:9090/proxy
PASS: grafana service accessible via http://127.0.0.1:52812/api/v1/namespaces/lightbend/services/expose-grafana:3000/proxy
PASS: alertmanager accessible via http://127.0.0.1:52812/api/v1/namespaces/lightbend/services/expose-alertmanager:9093/proxy
All smoke_proxy tests pass.  PASS: 4  FAIL: 0
PASS: timeseries: count( count by (instance) (ohai{workload="es-test", namespace="default"}) ) == 2
deployment.extensions "es-test" deleted
service "es-test" deleted
All smoke_prometheus tests pass.  PASS: 64  FAIL: 0
PASS: ES2 console accessible via http://192.168.99.100/es-console -H Host: minikube.ingress.test
All smoke_ingress tests pass.  PASS: 1  FAIL: 0
PASS: ES2 console accessible via https://192.168.99.100/es-console -H Host: tls.minikube.ingress.test -k
All smoke_ingress-tls tests pass.  PASS: 1  FAIL: 0
All tests completed with 0 failures

real	0m47.909s
user	0m8.558s
sys	0m3.634s
```

**Comment by dbrinegar** [comment]
Dunno why Travis didn't run until this cycle.  Needed the previous PR to merge first?  Anyway...

Curiously, the Travis run thinks that 0 + 0 + 0 + 0 + 0 == 1 test fail

```
All smoke_services tests pass.  PASS: 7  FAIL: 0
All smoke_proxy tests pass.  PASS: 4  FAIL: 0
All smoke_ingress tests pass.  PASS: 1  FAIL: 0
All smoke_ingress-tls tests pass.  PASS: 1  FAIL: 0
All smoke_prometheus tests pass.  PASS: 64  FAIL: 0
All tests completed with 1 failures
```

😕  will dig into that later

**Comment by dbrinegar** [comment]
ah, port forward is flaky now.  some console issue hid the output, need to sort that out in this PR I guess

**Comment by dbrinegar** [comment]
ready for review

**Comment by jsravn** [comment]
@dbrinegar I think travis captures console output to obfuscate secrets, which is probably why there may be some issues with stdout. I think there are solutions for it.

**Comment by jsravn** [comment]
ginkgo can run specs in parallel btw, if we intend on replacing bash w/ golang based test framework.

**Pull request merged**
